README.md

Repo team test

---

README.md

add team information to readme

add team information to readme

---

README.md

Added criteria, goals, and technologies used for the project. Also removed duplicates from the table of content

Amended the readme

---

home/templates/index.html
home/urls.py
home/views.py
pridefulproject/settings.py
pridefulproject/urls.py
templates/base.html

- Configure urls to render home page template
- Add Heroku link to allowed hosts for deployment

Deployment

---

templates/base.html
templates/includes/footer.html
templates/includes/header.html

Add includes folder
move footer.html to folder
add header.html to folder

Add includes folder, move footer, add header

---

templates/includes/header.html

edit navbar link titles to reflect app changes

---

home/templates/index.html

added content to html page and changed a button name

Lk prideful branch

---

README.md

Added Sophie to the credit line for creating a logo for us.

Add credit line in the readme

---

templates/includes/footer.html

The content adjusted in the footer is to show that the website is a school project for educational purposes

footer: adjusted content in the footer

---

static/css/style.css
templates/base.html
templates/includes/footer.html
templates/includes/header.html

- Adjust style for navbar
- Remove icons styling
- Tidy css
- Remove copyright from footer (we cannot copyright a webapp if it has content that we did not create without respective permission)
- Adjust text order in footer
- Adjust burger menu in header
- Adjust logo image in header
- Adjust home links in header
- Correct css reference link in base.html

Adjust navbar, footer, logo, base.html css reference

---

static/css/style.css

Applied secondary color to button border color.

Override button border color with custom css

---

templates/base.html

reorder css links in base.html

Rearrange order css link test

---

home/templates/index.html
static/css/style.css

Adjust background image container and image on landing page

adjust accent background image

---

static/css/style.css

chore: css tidy

---

pridefulproject/settings.py

Add whitenoise to middleware for deployment

Whitenoise

---

static/css/style.css

- Edit font size of the accent font text.

Change accent slogan text size

---

templates/includes/header.html
venues/views.py

- Link venues & contact nav links to their templates

Venues & Contact

---

home/templates/index.html
static/css/style.css

- Adjust font size for large screen media query 
- Edit colour for the card footer

Edit font size for the categories and add style for card footer

---

home/templates/index.html
static/css/style.css

- Add custom footer to index.html
- Add gradient to custom stylesheet

Add gradient to card footer

---

contact/static/contact_style.css
contact/templates/contact.html
static/css/style.css

- Added styling to the contact page
- Added a contact_style.css file

Contact page styling

---

static/css/style.css

Add background gradient to soften white background
Add subtle button styling

Add background gradient and button styling to index.html

---

contact/static/css/contact_style.css
contact/templates/contact.html
contact/templates/thankyou.html
contact/urls.py
contact/views.py

- Edited contact page styling
- Added a thank you page
- Added logic to redirect the user to the contact page if they attempt to access the thank you page without submitting the contact form

Contact & thank you pages

---

static/css/style.css
templates/includes/footer.html

- Add custom style to footer
- Adjust footer layout

Add style to footer

---

static/css/style.css
templates/includes/footer.html

- adjust hover over effects
- adjust html code

Change social media styles

---

static/css/style.css

- Adjust button styles
- Tidy css

Adjust button styles tidy css

---

static/css/style.css
templates/includes/footer.html

Adjust footer styles

---

templates/about.html

Add blurb text

---

venues/templates/venue_list.html

- Added styling & cards for the venues

Venue list 

---

home/templates/index.html
templates/about.html

Add load static to about.html
Update image refs on about.html page
Update hero image ref on index.html page

Update image refs

---

home/templates/index.html
static/css/style.css

Delete background image
Add different background image

Adjust hero image and background image on landing page

---

home/templates/index.html
templates/404.html
templates/500.html
templates/about.html
templates/includes/footer.html
templates/includes/header.html

- Add missing aria labels
- Correct hyperlink in the about page
- Correct button content in the landing page

Aria labels and content corrections

---

home/templates/index.html

Add links to venue pages

---

home/templates/index.html

Edit alt text in index html

---

templates/about.html

Edit about page section

---

contact/templates/contact.html
contact/templates/thankyou.html

- Add js to redirect to the home page from the thank you page 5 seconds after form submission
- Add button to the thank you page to redirect to the home page

Add timeout & button to redirect to the home page

---

contact/templates/contact.html
venues/templates/venue_list.html
venues/views.py

- Added tabs to the venue page to display venues by category
- Added some commented out code back in

Venue page tabs

---

README.md

- Edited out repeated colour palette mention in the readme.

Remove duplicate colour palette mention

---

home/templates/index.html
venues/templates/venue_list.html
venues/views.py

- Add selected_category context
- Add filters to the buttons on the landing page to direct the user to the correct tab on the venues page

Landing page buttons

---

contact/static/css/contact_style.css
templates/about.html
venues/templates/venue_list.html
venues/views.py

- Add to the about section
- Add website link to venue cards

About section, venue cards

---

static/css/style.css
venues/templates/venue_list.html

Adjust cards so that images are uniform

Adjust card image styling on venues page

---

README.md

- Correct spelling in the table of content so that the link works.

Edit link in the README.md

---

templates/base.html

Correct closing tag error introduced in recent pr

---

README.md

Add deployement to content page to README.md
